### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Benji1312** [ArpitxGit/Blockchain-Powered-eSIM#1]
Can someone please help me with this. Without giving me more trouble

**Comment by ArpitxGit** [comment]
> Can someone please help me with this. Without giving me more trouble

Sure, can you give me more context, where do you need help?

**Comment by ArpitxGit** [comment]
> Can someone please help me with this. Without giving me more trouble

Sure, can you give me more context, where do you need help @Benji1312 ?

**Comment by ArpitxGit** [comment]
Closing this issue as it isn't clear where @Benji1312 needs help and haven't responded in a long time.
